name: Build
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '**' # matches all branch
  schedule:
    - cron: '0 22 * * 6'  # every week at 22:00 on Saturday
      branches: 
       - master

jobs:
  lint-test-build:
    name: Lint & Test & Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [10.13.x, 12.x, 13.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Setup Node
        uses: actions/setup-node@v1.1.0
        with:
          node-version: ${{ matrix.node }}
      
      - name: Lint
        run: |
          yarn install
          yarn lint

      - name: Test
        run: yarn test

      - name: Build 
        run: yarn build


